### ISSUE TITLE
image download indicator on header bar

### ISSUE THREAD

**Issue by allaeddineomc** [marhkb/pods#305] opened 2022-09-10 23:17 UTC
when the user exits the page that appears when downloading an image there is no indication that the image is downloading and no way to cancel or to know when it errors out (may happen on bad internet connections) , an indicator can be like the one in boxes (when downloading ISOs) or the one in epiphany (when downloading anything)

**Comment by marhkb** [comment] 2022-09-11 11:14
Seems like a duplicate of #159

**Closed by marhkb** 2022-09-11 11:14 UTC
