### ISSUE TITLE
Pods on Fedora Silverblue?

### ISSUE THREAD

**Issue by iamgitcat** [marhkb/pods#732] opened 2023-11-01 10:29 UTC
Pods (with local connection) work only if Podman Desktop is running. Maybe some solution is possible on immutable system, I could not manage to run local connection in Pods without Podman Desktop.

If I try to connect without Podman Desktop running:
`error trying to connect: No such file or directory (os error 2)`

If I close Podman Desktop when Pods running:
`Connection lost: error reading a body from connection: unexpected EOF during chunk size line`

The default `unix:///run/user/1000/podman/podman.sock` is no such file
I found 2:
`/usr/lib/systemd/system/podman.socket`
`/usr/lib/systemd/user/podman.socket`

### Environment

- Pods version: 1.2.3
- Podman Version 4.7.0
- Fedora Silverblue 39

**Comment by marhkb** [comment] 2023-11-01 16:10
Hi! I'm using Silverblue, too. Most likely not a bug in Pods.

This is most likely because Podman Desktop is doing something nasty to the socket that it shouldn't be doing. You should report this in their issue tracker.

See this video. The socket is dead after closing Podman Desktop. Pods and curl doesn't work any more.

[Bildschirmaufzeichnung vom 2023-11-01, 17-06-55.webm](https://github.com/marhkb/pods/assets/3630213/ccc3fed8-8737-43b7-af61-c07275648d9f)

You can re-activate the socket by issuing:
```
systemctl --user restart podman.socket
```

**Closed by marhkb** 2023-11-01 16:10 UTC
Labels: not our bug

**Comment by frandavid100** [comment] 2023-11-15 08:14
I'd like to ask @iamgitcat, did you end up opening that issue? Would you care to provide a link?

**Comment by frandavid100** [comment] 2023-11-15 09:54
> This works `systemctl --user restart podman.socket`

Curiously, that seemed to work when I first tried it yesterday but not after a reboot. Then, Pods wasn't able to connect even after running the command repeatedly.

Is there any useful info I can give about that?

**Comment by marhkb** [comment] 2023-12-10 15:02
@frandavid100 
You could use a TCP socket if nothing else works (see https://gitlab.gnome.org/Teams/Circle/-/issues/150#note_1926675).

**Comment by jkemp814** [comment] 2023-12-11 15:58
I'm having problems also even though I have the socket running. When I enter my hostname (HP-Z840) I get that error message. I tried local, localhost, http://127.0.0.1. What I'm I suppose to enter the NAME field. I have seen another post asking if all this can be setup automatically, because some of us without docs, are familiar with how to set this all up. I prefer to use this package due to you all trying to keep it consistent with GNOME.

I'm I supposed to have the system-wide podman.socket enabled also? Currently, it's disabled, only the --user socket is enabled and running.

**Comment by jkemp814** [comment] 2023-12-11 16:37
Thank you for the thorough response, although I'm still confused. I remember now trying to use this a while back and couldn't get it going. I dislike software where right from the start there is a problem. Maybe it's a Silverblue and Flatpak thing. I appreciate the leads. Will follow up and see where it goes.

**Comment by jkemp814** [comment] 2023-12-11 16:45
I will. Thank you. Will this let me see all my Toolboxes? I have Three. fedora-toolbox-39, fedora-develop-39 and fedora-transcode-39?

**Comment by marhkb** [comment] 2023-12-11 17:30
> I'm having problems also even though I have the socket running. When I enter my hostname (HP-Z840) I get that error message. I tried local, localhost, http://127.0.0.1. What I'm I suppose to enter the NAME field. I have seen another post asking if all this can be setup automatically, because some of us without docs, are unfamiliar with how to set this all up. I prefer to use this package due to you all trying to keep it consistent with GNOME.
> 
> I'm I supposed to have the system-wide podman.socket enabled also? Currently, it's disabled, only the --user socket is enabled and running.

The name field is not relevant. You can enter anything there you want.

No idea, how you started the TCP socket. But if you used this command

```
podman system service --time=0 tcp://localhost:8888
```

then you shouldn't use the HTTP protocol.

The correct URL would be:

```
tcp://localhost:8888
```

or

```
tcp://127.0.0.1:8888
```

![grafik](https://github.com/marhkb/pods/assets/3630213/a916e2cd-77b6-496b-97d1-5263c83e905d)

**Comment by amilganju** [comment] 2024-07-26 21:11
I was facing the same issue and I seem to have found the solution. So even though this issue is closed it might help some other users.
The root cause is that the Flatpak needs to be given explicit read permissions to the directory containing the user socket i.e. **/run/user/1000/podman**
